### ISSUE TITLE
Wiki page 작성

### ISSUE THREAD

**Issue by rnin9** [rnin9/Project2#13]
Wiki page를 작성합니다.

**Comment by minhodang** [comment]
확인했습니다.

**Comment by rnin9** [comment]
Home 작성했습니다. 이외 본인이 작성한 코드에 대한 목차를 Home에 추가해 주세요.
링크 첨부해 드립니다.

[Wiki Home](https://github.com/rnin9/Project2/wiki)

**Comment by rnin9** [comment]
wiki page 구현 부분 작성 완료했습니다. 나머지 팀원 분들도 wiki page 작성 해 주세요

**Comment by gulike7** [comment]
wiki page 구현부분 작성했습니다
