### ISSUE TITLE
파일 수정시간 비교 코드 테스팅

### ISSUE THREAD

**Issue by gulike7** [rnin9/Project2#17]

**Comment by minhodang** [comment]
확인했습니다.

**Comment by gulike7** [comment]
<(월/일), (시/분) 이 다를때>
![image](https://user-images.githubusercontent.com/35617396/82429771-66145780-9ac7-11ea-9870-faa0edf933d9.png)
<(월/일), (시/분) 이 같을때>
![image](https://user-images.githubusercontent.com/35617396/82430002-b5f31e80-9ac7-11ea-97e1-2dcbf19a8341.png)

날짜 비교, 시간 비교가 잘 됨을 확인할 수 있다.
