### ISSUE TITLE
파일 시간 받아오는 전역변수 포인터 문제

### ISSUE THREAD

**Issue by rnin9** [rnin9/Project2#20]
전역변수 포인터 struct *time1 , *time2 가 다른 함수 내에서 실행되는 경우 제대로 동작하지 않음 .

**Comment by rnin9** [comment]
![image](https://user-images.githubusercontent.com/62874963/81314266-e13b3e00-90c3-11ea-944e-07337157ffb6.png)


전역변수포인터  struct *time1 , *time2  을 위와 같이 struct tm time1, time2로 변경.


![image](https://user-images.githubusercontent.com/62874963/81314440-13e53680-90c4-11ea-85f5-fbdf5a8a6beb.png)

filetime1, 2 함수를 위와같이 timecheck 변수로 확인 한 뒤, 이상이 없는 경우 

 time1 = *localtime(&stat1.st_mtime);
 time2 = *localtime(&stat2.st_mtime);


위처럼 변경,

**Comment by rnin9** [comment]
![image](https://user-images.githubusercontent.com/62874963/81314695-63c3fd80-90c4-11ea-9608-a722ac831a34.png)


text1 text2 의 변경시간중 분의 시간을 확인 ( 5 , 8 )
![image](https://user-images.githubusercontent.com/62874963/81315041-c5846780-90c4-11ea-9819-e07b1b20c03e.png)

__________________________________________________________________________________________________

< 변경전 > 

![image](https://user-images.githubusercontent.com/62874963/81315240-07151280-90c5-11ea-9213-6e01f91cb108.png)



< 변경 후 >

![image](https://user-images.githubusercontent.com/62874963/81315330-24e27780-90c5-11ea-9321-4d47e9136104.png)

**Comment by gulike7** [comment]
수정 확인했습니다

**Comment by minhodang** [comment]
확인했습니다.
