### ISSUE TITLE
코드 실행 결과

### ISSUE THREAD

**Issue by minhodang** [rnin9/Project2#26]
일 크기를 비교하는 함수 작성

1.실행결과
![2](https://user-images.githubusercontent.com/38343803/82431127-38c8a900-9ac9-11ea-8bbc-ec1cc29163e8.JPG)

2.실제 파일 사이즈(터미널)
![3](https://user-images.githubusercontent.com/38343803/82431135-3a926c80-9ac9-11ea-8cf1-d968e7b90088.JPG)

**Comment by rnin9** [comment]
확인했습니다.

**Comment by gulike7** [comment]
확인했습니다
