### ISSUE TITLE
코드 실행 결과

### ISSUE THREAD

**Issue by minhodang** [rnin9/Project2#27]
파일 크기를 비교하는 함수 작성

1. 실행결과
![2](https://user-images.githubusercontent.com/38343803/82431373-880ed980-9ac9-11ea-8422-fc5cd5722aff.JPG)

2. 실제 파일 사이즈(터미널)
![3](https://user-images.githubusercontent.com/38343803/82431384-89400680-9ac9-11ea-852d-bf6ba1a64d63.JPG)

**Comment by rnin9** [comment]
확인했습니다.

**Comment by gulike7** [comment]
확인했습니다
