### ISSUE TITLE
파일 수정시간 비교 코드 테스팅

### ISSUE THREAD

**Issue by gulike7** [rnin9/Project2#28]
파일 수정시간을 테스팅한다.
동시 진행할 수 있는 파일 수정날짜도 동시에 테스팅한다

**Comment by gulike7** [comment]
<[월/일], [시/분] 이 다를 때> 
![image](https://user-images.githubusercontent.com/35617396/82431796-15522e00-9aca-11ea-894b-c8e5ecea3a2a.png)
<[월/일], [시/분] 이 같을 때>
![image](https://user-images.githubusercontent.com/35617396/82431822-213df000-9aca-11ea-891f-9f0ef2d4d260.png)



날짜 비교, 시간 비교가 잘 됬음을 확인했음.

**Comment by minhodang** [comment]
확인했습니다.
